CREATE TABLE products (
                          id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          sku         VARCHAR(50)    NOT NULL,
                          name        VARCHAR(255)   NOT NULL,
                          description VARCHAR(1000),
                          price       NUMERIC(12, 2) NOT NULL,
                          CONSTRAINT uk_products_sku UNIQUE (sku),
                          CONSTRAINT ck_products_price_non_negative CHECK (price >= 0)
);